version: "3.7"

services:
  mysql:
    image: mysql:8
    volumes:
    - "./volumes/mysql:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD_FILE: "/run/secrets/mysql_password"
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysql_root_password"
      MYSQL_DATABASE: "mydb"
    expose:
      - 3306
    secrets:
      - mysql_password
      - mysql_root_password
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.0-rc1
    hostname: redis
    networks:
      - backend
    volumes:
    - "./volumes/redis:/data"

networks:
  backend:

secrets:
  mysql_password:
    file: ./mysql_password_secret.txt
  mysql_root_password:
    file: ./mysql_root_password_secret.txt
